version: "3.9"

services:
  postgres:
    image: postgres:14
    environment:
      - POSTGRES_DB=django_blog
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - django_blog_db:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - DB_NAME=django_blog
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_PORT=5432
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - migrations
  migrations:
    build: .
    environment:
      - DB_NAME=django_blog
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_PORT=5432
    command: python manage.py migrate
    depends_on:
      - postgres

volumes:
  django_blog_db:
